/**************************************************************************** 
*
* alps/looper: multi-cluster quantum Monte Carlo algorithm for spin systems
*              in path-integral and SSE representations
*
* $Id: index_helper.C 454 2003-10-22 00:41:25Z wistaria $
*
* Copyright (C) 1997-2003 by Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.
*
* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include <looper/vector_helper.h>

#include <boost/random.hpp>
#include <iostream>

template<class C>
void check(const C& c)
{
  looper::index_helper<C> helper(c);
  for (int i = 0; i < c.size(); ++i) assert(i == helper.index(&c[i]));
}

int main()
{
  boost::mt19937 rng;
  boost::uniform_int<> uniform_int(1, 10);

  std::vector<int> a(100);
  check(a);
  std::cout << "std::vector(" << a.size() << ") OK\n";

  std::deque<int> b(uniform_int(rng));
  check(b);
  for (;;) {
    int n = uniform_int(rng);
    if (rng() < 0.5) {
      for (int i = 0; i < n; ++i) b.push_front(0);
    } else {
      for (int i = 0; i < n; ++i) b.push_back(0);
    }
    check(b);
    std::cout << "std::deque(" << b.size() << ") OK\n";
    if (b.size() > 300) break;
  }
  assert(looper::index_helper<>::index(b, &b[b.size() / 2]) == b.size() / 2);
}
