/**************************************************************************** 
*
* alps/looper: multi-cluster quantum Monte Carlo algorithm for spin systems
*              in path-integral and SSE representations
*
* $Id: permutation.C 447 2003-10-18 08:35:39Z wistaria $
*
* Copyright (C) 1997-2003 by Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.
*
* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include "permutation.h"
#include <boost/random.hpp>
#include <algorithm> // for std::random_shuffle
#include <cstdlib>
#include <iostream>
#include <vector>

const unsigned int n = 10;
const unsigned int trial1 = 20;
const unsigned int trial2 = 5;
const boost::uint32_t seed = 23094;

int main() {
  typedef boost::mt19937 rng_type;
  typedef boost::uniform_01<rng_type> uniform_01;
  typedef boost::uniform_smallint<> uniform_smallint;
  typedef boost::random_number_generator<rng_type> shuffle_rng;

  typedef std::vector<unsigned int> vector_type;

  rng_type rng(seed);

  std::cout << "[[random permutaion test 1]]\n";
  // shuffle_rng sr(rng);

  std::cout << "generating " << trial1 << " random permutations of " 
       << n << " integers [0..." << n - 1 << "]\n";

  for (unsigned int i = 0; i < trial1; ++i) {
    vector_type result(n);
    for (unsigned int j = 0; j < n; ++j) result[j] = j;
    looper::random_shuffle(result.begin(), result.end(), rng);
    for (unsigned int j = 0; j < n; ++j) {
      std::cout << result[j] << '\t';
    }
    std::cout << std::endl;
  }
  
  std::cout << "\n[[random permutaion test 2 (with restrictions)]]\n";

  std::cout << "generating " << trial2 << " restricted random permutations\n" ;

  for (unsigned int t = 0; t < trial2; t++) {
    vector_type config0(n);
    for (unsigned int i = 0; i < n; i++) {
      config0[i] = uniform_smallint(0, 1)(rng);
    }
    vector_type config1(config0);
    looper::random_shuffle(config1.begin(), config1.end(), rng);

    std::cout << "conf0";
    for (unsigned int i = 0; i < n; i++) std::cout << '\t' << config0[i];
    std::cout << std::endl;
    
    std::cout << "conf1";
    for (unsigned int i = 0; i < n; i++) std::cout << '\t' << config1[i];
    std::cout << std::endl;
    
    vector_type result(n);
    for (unsigned int j = 0; j < n; ++j) result[j] = j;

    // generate restricted permutation
    looper::restricted_random_shuffle(result.begin(), result.end(),
				      config0.begin(), config0.end(),
				      config1.begin(), config1.end(),
				      rng);

    std::cout << "perm";
    for (unsigned int i = 0; i < n; i++) std::cout << '\t' << result[i];
    std::cout << std::endl;

    std::cout << "check";
    int chk = 0;
    for (unsigned int i = 0; i < n; i++) {
      std::cout << '\t' << (config0[i] ^ config1[result[i]]);
      chk += (config0[i] ^ config1[result[i]]);
    }
    std::cout << std::endl;
    if (chk > 0) { std::cout << "Error occurs!  Stop.\n"; std::exit(-1); }

    std::cout << std::endl;
  }
} 
