#!/bin/sh

if test -f configure.ac; then :; else
  echo "configure.ac not found.  Stop."
  exit -1
fi

# required version of autotools
am_require=1.9.5
ac_require=2.59
lt_require=1.5.18

am_version=`automake --version 2>&1 | head -1 | cut -d ' ' -f 4`
ac_version=`autoconf --version 2>&1 | head -1 | cut -d ' ' -f 4`
lt_version=`libtoolize --version 2>&1 | head -1 | cut -d ' ' -f 4`

have_autotools=yes
if test "x$am_version" != "x$am_require"; then
  echo "Error: automake version $am_require is required, but found $am_version."
  have_autotools=no
fi
if test "x$ac_version" != "x$ac_require"; then
  echo "Error: autoconf version $ac_require is required, but found $ac_version."
  have_autotools=no
fi
if test "x$lt_version" != "x$lt_require"; then
  echo "Error: libtool version $lt_require is required, but found $lt_version."
  have_autotools=no
fi
if test "$have_autotools" = no; then
  echo "Stop."
  exit -1
fi

if test -d config; then
  aclocal_flags='-I config'
  patch_flags=-p0
else
  patch_flags=-p1
fi

set -x
aclocal $aclocal_flags
libtoolize --force --copy
find . -name config.h.in | xargs touch
automake --foreign --add-missing --copy
autoconf
rm -rf autom4te.cache

# patch to libtool (workaround for 1.5.16)
# uudecode -p << EOF | gzip -dc | patch $patch_flags
# begin-base64 644 ltmain.patch.gz
# H4sICGezbUIAA2x0bWFpbi5wYXRjaACdUUFugzAQPMMrNlEuoXEKBqyUKIf+oXdkNYZaMQY5SSP1
# 9QW7BhOKFGUPtna9M56dDYIAPmtZ8PJVXCrK5fb8ta0VL72PK4P3RgEmEIVZgjP8BjgMUx8hNIGM
# unEWxVmYmu5gHF0OUZySTRSTGHQJwIOO8cLllZlsv29vG0eqblzmhaIVu9XqtPYXBlE1XDCVF4KW
# 58NyNS7Aiqpyaegaxb4Ps/94wVoPZWURaDP0rCzB5ckR5aaA+uY/dQ8NMkE5M704BHl7V1QeBwZb
# mVJoXMElFfzHBd6XZj6fcfHfZSc43LQHscvuLUSOdYOteq57b33Uvz+69qG/l2pD6zUrT3DciduZ
# lf8CtTiWZg4DAAA=
# ====
# EOF
