#!/bin/sh

force_version=yes
if test "$1" == '--skip-check'; then
  force_version=no
fi

if test -f configure.ac; then :; else
  echo "Error: configure.ac not found." 1>&2
  exit -1
fi

# required version of autotools
am_require=1.10.2
ac_require=2.63
lt_require=1.5.26
if `(grep AC_PROG_LIBTOOL configure.ac) > /dev/null 2>&1`; then
  if `(glibtoolize --version) > /dev/null 2>&1`; then
    LIBTOOLIZE=glibtoolize
  else
    LIBTOOLIZE=libtoolize
  fi
else
  LIBTOOLIZE=
fi

if test "x$force_version" = xyes; then
  am_version=`automake --version 2>&1 | head -1 | cut -d ' ' -f 4`
  ac_version=`autoconf --version 2>&1 | head -1 | cut -d ' ' -f 4`
  if test -n "$LIBTOOLIZE"; then
    lt_version=`$LIBTOOLIZE --version 2>&1 | head -1 | cut -d ' ' -f 4`
  fi

  have_autotools=yes
  if test "x$am_version" != "x$am_require"; then
    echo "Error: automake version $am_require is required, but found $am_version." 1>&2
    have_autotools=no
  fi
  if test "x$ac_version" != "x$ac_require"; then
    echo "Error: autoconf version $ac_require is required, but found $ac_version." 1>&2
    have_autotools=no
  fi
  if test -n "$LIBTOOLIZE"; then
    if test "x$lt_version" != "x$lt_require"; then
      echo "Error: libtool version $lt_require is required, but found $lt_version." 1>&2
      have_autotools=no
    fi
  fi
  if test "$have_autotools" = no; then
    exit -1
  fi
fi

if test -d config; then
  aclocal_flags='-I config'
fi

scripts="configu.guess consig.sub depcomp install-sh ltmain.sh mkinstalldirs missing"
if test -d config; then
  for s in $scripts; do
    test -f "config/$s" && rm -f "config/$s"
  done
else
  for s in $scripts; do
    test -f "$s" && rm -f "$s"
  done
fi  

echo aclocal $aclocal_flags
     aclocal $aclocal_flags
[ "$?" -ne 0 ] && exit $?

if test -n "$LIBTOOLIZE"; then
  echo $LIBTOOLIZE --force --copy
       $LIBTOOLIZE --force --copy
  [ "$?" -ne 0 ] && exit $?
fi

CONFIG_H=`find . -name config.h.in`
for c in $CONFIG_H; do
  echo touch $c
       touch $c
done

echo automake --foreign --add-missing --copy
     automake --foreign --add-missing --copy
[ "$?" -ne 0 ] && exit $?

echo autoconf
     autoconf
[ "$?" -ne 0 ] && exit $?

rm -rf autom4te.cache
