/**************************************************************************** 
*
* alps/looper: multi-cluster quantum Monte Carlo algorithm for spin systems
*              in path-integral and SSE representations
*
* $Id: copyright.C 552 2003-11-12 02:00:01Z wistaria $
*
* Copyright (C) 1997-2003 by Synge Todo <wistaria@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.
*
* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include "looper/copyright.h"
#include <boost/throw_exception.hpp>
#include <iostream>
#include <stdexcept>

struct options
{
  bool license;

  options(int argc, char *argv[]) : license(false) { parse(argc, argv); }

  void usage(int status, std::ostream& os = std::cerr) const
  {
    os << "NAME\n"
       << "     copyright - print copyright and/or license information\n\n"
       << "SYNOPSIS\n"
       << "     copyright [-l] [-h]\n\n"
       << "DESCRIPTION\n"
       << "     The options are as follows:\n\n"
       << "     -l          print license details.\n"
       << "     -h          print this help message and exit.\n\n";
    if (status) {
      boost::throw_exception(std::invalid_argument("Invalid command line option(s)"));
    } else {
      std::exit(0);
    }
  }

  void parse(int argc, char *argv[]) {
    for (int i = 1; i < argc; ++i) {
      switch (argv[i][0]) {
      case '-' :
        switch (argv[i][1]) {
        case 'l' :
	  license = true;
          break;
        case 'h' :
	  usage(0, std::cout);
          break;
	default :
	  usage(1);
	  break;
	}
	break;
	
      default :
	usage(1);
	break;
      }
    }
  }
};


int main(int argc, char *argv[])
{
#ifndef BOOST_NO_EXCEPTIONS
try {
#endif

  options opts(argc, argv);
  looper::print_copyright(std::cout);
  alps::print_copyright(std::cout);
  if (opts.license) looper::print_license(std::cout);

#ifndef BOOST_NO_EXCEPTIONS
} 
catch (const std::exception& excp) {
  std::cerr << excp.what() << std::endl;
  std::exit(-1); }
catch (...) {
  std::cerr << "Unknown exception occurred!" << std::endl;
  std::exit(-1); }
#endif
}
