/**************************************************************************** 
*
* alps/looper: multi-cluster quantum Monte Carlo algorithm for spin systems
*              in path-integral and SSE representations
*
* $Id: fill_duration.C 442 2003-10-18 03:00:15Z wistaria $
*
* Copyright (C) 1997-2003 by Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.
*
* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include "random.h"

#include <alps/alea.h>
#include <boost/random.hpp>
#include <iostream>

int main()
{
#ifndef BOOST_NO_EXCEPTIONS
try {
#endif

  double r, tmax;
  int trial;
  std::cin >> r >> tmax >> trial;

  boost::mt19937 base_rng;
  boost::uniform_01<boost::mt19937> uniform_01(base_rng);
  for (int i = 0; i < trial; ++i) uniform_01();

  std::cout << "filling duration [0," << tmax << "]\n";
  std::vector<double> a;
  looper::fill_duration(uniform_01, a, r, tmax);
  for (std::vector<double>::iterator itr = a.begin(); itr != a.end(); ++itr) {
    std::cout << *itr << ' ';
  }
  std::cout << std::endl;
  
  std::cout << "filling duration " << trial << " times\n";
  alps::BasicSimpleObservable<double, alps::NoBinning<double> >
    n("average density");
  n.reset(true);
  for (int i = 0; i < trial; ++i) {
    looper::fill_duration(uniform_01, a, r, tmax);
    n << a.size() / tmax;
  }
  std::cout << n;
  std::cout << "exact density: " << r << std::endl;

#ifndef BOOST_NO_EXCEPTIONS
}
catch (std::exception& exc) {
  std::cerr << exc.what() << "\n";
  return -1;
}
catch (...) {
  std::cerr << "Fatal Error: Unknown Exception!\n";
  return -2;
}
#endif
}
