amida.o amida_mpi.o amida_pvm.o amida amida_mpi amida_pvm: $(srcdir)/amida.h
permutation.o permutation_mpi.o permutation_pvm.o permutation permutation_mpi permutation_pvm: $(srcdir)/permutation.h
simplegraph.o simplegraph_mpi.o simplegraph_pvm.o simplegraph simplegraph_mpi simplegraph_pvm: $(srcdir)/graph.h
virtualgraph.o virtualgraph_mpi.o virtualgraph_pvm.o virtualgraph virtualgraph_mpi virtualgraph_pvm: $(srcdir)/graph.h $(srcdir)/virtualgraph.h
xxz_matrix.o xxz_matrix_mpi.o xxz_matrix_pvm.o xxz_matrix xxz_matrix_mpi xxz_matrix_pvm: $(srcdir)/xxz.h
xxz_model.o xxz_model_mpi.o xxz_model_pvm.o xxz_model xxz_model_mpi xxz_model_pvm: $(srcdir)/xxz.h
