/**************************************************************************** 
*
* alps/percolation: an ALPS application example for percolation problem
*
* $Id: percolation_cmd.C 455 2003-10-22 01:04:57Z wistaria $
*
* Copyright (C) 1997-2003 by Synge Todo <wistaria@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.
*
* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include <looper/graph.h>
#include <looper/percolation.h>

#include <alps/alea.h>
#include <boost/random.hpp>
#include <iostream>

struct Options {
  uint32_t seed;         // -r seed
  bool     bond;         // -b whether bond percolation or not
  uint32_t dim;          // -d spatial dimension
  uint32_t lsize;        // -l linear size of system
  uint32_t nm;           // -m number of samples
  double   p;            // -p occupation probability
  
  Options(int argc, char *argv[]) : 
    // default options
    seed(2837), bond(false), dim(2), lsize(32), nm(128), p(-1)
  {
    parse(argc, argv);
  }
  
  void usage(int status, std::ostream& os = std::cerr) const {
    os << "[command line options]\n\n"
       << "  -p double  concentration (REQUIED)\n"
       << "  -r int     seed of random number generator (2837)\n"
       << "  -b         bond percolation (false)\n"
       << "  -d int     spatial dimension (2)\n"
       << "  -l int     linear size of system (32)\n"
       << "  -m int     number of samples (128)\n"
       << "  -h         this help\n\n";
    if (status) {
      boost::throw_exception(std::invalid_argument("Invalid command line option(s)"));
    } else {
      std::exit(0);
    }
  }

  void parse(int argc, char *argv[]) {
    bool found_p = false;
    for (int i = 1; i < argc; ++i) {
      switch (argv[i][0]) {
      case '-' :
        switch (argv[i][1]) {
        case 'r' :
	  if (i + 1 == argc) usage(1);
          seed = std::atoi(argv[++i]);
          break;
        case 'b' :
          bond = true;
          break;
        case 'd' :
	  if (i + 1 == argc) usage(1);
          dim = std::atoi(argv[++i]);
          break;
        case 'l' :
	  if (i + 1 == argc) usage(1);
          lsize = std::atoi(argv[++i]);
          break;
        case 'm' :
	  if (i + 1 == argc) usage(1);
          nm = std::atoi(argv[++i]);
          break;
        case 'p' :
	  if (i + 1 == argc) usage(1);
          p = std::atof(argv[++i]);
	  found_p = true;
          break;
	case 'h' :
	  usage(0);
	  break;
	default :
	  usage(1);
	  break;
	}
	break;
	
      default :
	usage(1);
	break;
      }
    }
    if (!found_p) usage(1);
  }
};


int main(int argc, char *argv[]) {

#ifndef BOOST_NO_EXCEPTIONS
try {
#endif

  std::cout << "[alps/looper: an ALPS application example for percolation problem]\n\n";

  // simulation parameters
  Options opts(argc, argv);
  std::cout << "r: seed for RNG           : " << opts.seed << std::endl;
  std::cout << "b: type                   : " << (opts.bond ? "bond" : "site") << " percolation\n";
  std::cout << "d: spatial dimension      : " << opts.dim << std::endl;
  std::cout << "l: linear size            : " << opts.lsize << std::endl;
  std::cout << "m: number of samples      : " << opts.nm << std::endl;
  std::cout << "p: concentration          : " << opts.p << std::endl
	    << std::endl;

  // random number generator
  boost::mt19937 base_rng;
  boost::uniform_01<boost::mt19937> rng(base_rng);
  rng.base().seed(boost::mt19937::result_type(opts.seed));
  for (int i = 0; i < 19844; ++i) rng();

  // hypercubic lattice
  typedef looper::graph_type graph_type;
  typedef graph_type::edge_iterator edge_iterator;
  typedef graph_type::vertex_iterator vertex_iterator;
  typedef graph_type::vertex_descriptor vertex_descriptor;
  
  looper::simple_hypercubic_graph_descriptor<> shgd(opts.dim, opts.lsize);
  graph_type graph;
  looper::generate_graph(shgd, graph);

  // measurements
  alps::ObservableSet measurements;

  if (opts.bond) {
    // bond percolation
    looper::percolation::bond bp(graph, opts.p, measurements);
    for (int s = 0; s < opts.nm; s++) bp.step(graph, rng, measurements);
  } else {
    // site percolation
    looper::percolation::site sp(graph, opts.p, measurements);
    for (int s = 0; s < opts.nm; s++) sp.step(graph, rng, measurements);
  }
  
  // output results
  std::cout << measurements;

#ifndef BOOST_NO_EXCEPTIONS
} 
catch (const std::exception& excp) {
  std::cerr << excp.what() << std::endl;
  std::exit(-1); }
catch (...) {
  std::cerr << "Unknown exception occurred!" << std::endl;
  std::exit(-1); }
#endif
}
