/**************************************************************************** 
*
* alps/looper: multi-cluster quantum Monte Carlo algorithm for spin systems
*              in path-integral and SSE representations
*
* $Id: simple_pi.C 432 2003-10-16 13:24:54Z wistaria $
*
* Copyright (C) 2001-2003 by Synge Todo <wistaria@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.
*
* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include "graph.h"
#include "pathintegral.h"
#include "random.h"
#include "virtualgraph.h"
#include "xxz.h"

#include <alps/alea.h>
#include <iostream>

struct Options {
  uint32_t seed;                // -r seed
  uint32_t dim;                 // -d spatial dimension
  uint32_t lsize;               // -l linear size of system
  alps::half_integer<int> spin; // -s spin size S
  double Jxy;                   // -x coupling Jxy (positive for ferromagnetic)
  double Jz;                    // -z coupling Jz (positive for ferromagnetic)
  double temp;                  // -t temperature
  uint32_t step_t;              // -m MCS for thermalization
  uint32_t step_m;              // -n MCS for measurement
  
  Options(int argc, char *argv[]) : 
    // default options
    seed(2837), dim(1), lsize(16), spin(0.5), Jxy(-1.), Jz(-1.), temp(1.),
    step_t(1024), step_m(8192)
  {
    parse(argc, argv);
  }
  
  void usage(int status, std::ostream& os = std::cerr) const {
    os << "[command line options]\n\n"
       << "  -r int     seed of random number generator\n"
       << "  -d int     spatial dimension\n"
       << "  -l int     linear size of system\n"
       << "  -s double  spin size S\n"
       << "  -x double  coupling Jxy\n"
       << "  -z double  doupling Jz\n"
       << "  -t double  temperature\n"
       << "  -m int     MCS for thermalization\n"
       << "  -n int     MCS for measurement\n"
       << "  -h         this help\n\n";
    if (status) {
      boost::throw_exception(std::invalid_argument("Invalid command line option(s)"));
    } else {
      std::exit(0);
    }
  }

  void parse(int argc, char *argv[]) {
    for (int i = 1; i < argc; ++i) {
      switch (argv[i][0]) {
      case '-' :
        switch (argv[i][1]) {
        case 'r' :
	  if (i + 1 == argc) usage(1);
          seed = std::atoi(argv[++i]);
          break;
        case 'd' :
	  if (i + 1 == argc) usage(1);
          dim = std::atoi(argv[++i]);
          break;
        case 'l' :
	  if (i + 1 == argc) usage(1);
          lsize = std::atoi(argv[++i]);
          break;
        case 's' :
	  if (i + 1 == argc) usage(1);
          spin = alps::half_integer<int>(std::atof(argv[++i]));
          break;
        case 'x' :
	  if (i + 1 == argc) usage(1);
          Jxy = std::atof(argv[++i]);
          break;
        case 'z' :
	  if (i + 1 == argc) usage(1);
          Jz = std::atof(argv[++i]);
          break;
        case 't' :
	  if (i + 1 == argc) usage(1);
          temp = std::atof(argv[++i]);
          break;
        case 'm' :
	  if (i + 1 == argc) usage(1);
          step_t = std::atoi(argv[++i]);
          break;
        case 'n' :
	  if (i + 1 == argc) usage(1);
          step_m = std::atoi(argv[++i]);
          break;
	case 'h' :
	  usage(0);
	  break;
	default :
	  usage(1);
	  break;
	}
	break;
	
      default :
	usage(1);
	break;
      }
    }
  }
};


int main(int argc, char *argv[]) {

#ifndef BOOST_NO_EXCEPTIONS
try {
#endif

  std::cout << "[alps/looper: multi-cluster quantum Monte Carlo algorithm for spin systems\n"
	    << "              in path-integral and SSE representations]\n\n";

  // simulation parameters
  Options opts(argc, argv);
  std::cout << "r: seed for RNG           : " << opts.seed << std::endl
	    << "d: spatial dimension      : " << opts.dim << std::endl
	    << "l: linear size            : " << opts.lsize << std::endl
	    << "s: spin size S            : " << opts.spin << std::endl
	    << "x: coupling Jxy           : " << opts.Jxy << std::endl
	    << "z: doupling Jz            : " << opts.Jz << std::endl
	    << "t: temperature            : " << opts.temp << std::endl
	    << "m: MCS for thermalization : " << opts.step_t << std::endl
	    << "n: MCS for measurement    : " << opts.step_m << std::endl
	    << std::endl;

  // random number generator
  boost::mt19937 base_rng;
  boost::uniform_01<boost::mt19937> rng(base_rng);
  rng.base().seed(boost::mt19937::result_type(opts.seed));
  for (int i = 0; i < 19844; ++i) rng();

  // hypercubic lattice
  typedef looper::graph_type graph_type;
  looper::simple_hypercubic_graph_descriptor<> shgd(opts.dim, opts.lsize);
  graph_type g;
  looper::generate_graph(shgd, g);

  // virtual graph
  looper::virtual_graph_type<graph_type>::graph_type vg;
  looper::virtual_graph_type<graph_type>::mapping_type vm;
  std::vector<alps::half_integer<int> > spin(opts.dim, opts.spin);
  looper::generate_virtual_graph(g, spin, vg, vm);

  // model
  looper::xxz_model model(opts.Jxy, opts.Jz, opts.spin, g);

  // world line configration
  looper::amida<looper::path_integral::node<> > config;
  looper::path_integral::initialize(config, vg, vm);

  // measurements
  alps::ObservableSet measurements;

  looper::path_integral::do_labeling(config, vg, vm, model, 1./opts.temp, rng);

  // output results
  std::cout << measurements;

#ifndef BOOST_NO_EXCEPTIONS
} 
catch (const std::exception& excp) {
  std::cerr << excp.what() << std::endl;
  std::exit(-1); }
catch (...) {
  std::cerr << "Unknown exception occurred!" << std::endl;
  std::exit(-1); }
#endif
}
