/**************************************************************************** 
*
* alps/looper: multi-cluster quantum Monte Carlo algorithm for spin systems
*              in path-integral and SSE representations
*
* $Id: unionfind.C 401 2003-10-09 14:57:41Z wistaria $
*
* Copyright (C) 2001-2003 by Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.
*
* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include "unionfind.h"
#include <boost/random.hpp>

#include <iostream>
#include <valarray>

#ifdef BOOST_NO_ARGUMENT_DEPENDENT_LOOKUP
using namespace looper;
#endif

const int n = 100;

template<class Itr0, class Itr1>
int index(const Itr0& itr, const Itr1& base) {
  return itr - base;
}

int main()
{
  typedef std::vector<looper::unionfind::node<> > vector_type;
  typedef boost::mt19937 rng_type;
  typedef boost::uniform_int<> uniform_int;

  rng_type rng;
  
  std::cout << "[[union find test]]\n";

  vector_type tree(n);

  std::cout << "\n[making tree]\n";

  for (int i = 0; i < n; i++) {
    int i0 = uniform_int(0, n-1)(rng);
    int i1 = uniform_int(0, n-1)(rng);
    std::cout << "connecting node " << i0 << " to node " << i1 << std::endl;
    unify(tree[i0], tree[i1]);
  }

  std::cout << "\n[results]\n";

  for (vector_type::iterator itr = tree.begin(); itr != tree.end(); ++itr) {
    if (itr->is_root()) {
      std::cout << "node " << index(itr, tree.begin())
		<< " is root and tree size is "
		<< itr->weight() << std::endl;
    } else {
      std::cout << "node " << index(itr, tree.begin());
      std::cout << "'s parent is " << index(itr->parent(), tree.begin());
      std::cout << " and its root is " << index(itr->root(), tree.begin())
		<< std::endl;
    }
  }
}
