/**************************************************************************** 
*
* alps/looper: multi-cluster quantum Monte Carlo algorithm for spin systems
*              in path-integral and SSE representations
*
* $Id: xxz_matrix.C 396 2003-10-09 09:03:24Z wistaria $
*
* Copyright (C) 2001-2003 by Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.
*
* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#include "xxz_matrix.h"
#include <iostream>

int main()
{
  int n;
  std::cin >> n;
  for (int i = 0; i < n; ++i) {
    double s0_in, s1_in, e0, jxy, jz;
    std::cin >> s0_in >> s1_in >> e0 >> jxy >> jz;
    alps::half_integer<int> s0(s0_in);
    alps::half_integer<int> s1(s1_in);
    looper::xxz_matrix<> xxz(s0, s1, e0, jxy, jz);

    std::cout << "input parameters: S0 = " << s0 << ", S1 = " << s1
	      << ", e0 = " << e0 << ", Jxy = " << jxy << ", Jz = " << jz
	      << std::endl << xxz << std::endl;

    boost::tuple<bool, double, double, double> fit =
      looper::fit2xxz(s0, s1, xxz);

    if (fit.get<0>()) {
      std::cout << "fitting result: e0 = " << fit.get<1>()
		<< ", Jxy = " << fit.get<2>()
		<< ", Jz = " << fit.get<3>()
		<< std::endl;
    } else {
      std::cout << "fitting failed\n";
    }
  }
}
