#! /bin/sh

# for echo without trailing newline character
case `echo "testing\c"; echo 1,2,3`,`echo -n testing; echo 1,2,3` in
  *c*,-n*) ECHO_N= ECHO_C='
' ;;
  *c*,*  ) ECHO_N=-n ECHO_C= ;;
  *)       ECHO_N= ECHO_C='\c' ;;
esac

if test -z "$2"; then
  echo usage: $0 srcdir program
  exit -1
fi

srcdir="$1"
prog=`basename $2 .exe`
dir=`echo $2 | sed 's/^\(\.\/\)*//g'` # remove preceding './'
if test -n "$dir"; then
  dir=`dirname ${dir}`
  srcdir="${srcdir}/${dir}"
  if test -d "$srcdir"; then :; else
    echo error: $srcdir not found
    exit -1
  fi
  if test -d "$dir"; then :; else
    echo error: $dir not found
    exit -1
  fi
  if test "$dir" != "."; then
    echo $ECHO_N "[$dir] $ECHO_C"
  fi
  cd $dir
  srcdir=`echo $srcdir | sed 's/^\./..\/./g'` # add '../' in case of relative path
fi

INPUT=
if test -f "${prog}.input"; then
  INPUT="${prog}.input"
elif test -f "${prog}.ip"; then
  INPUT="${prog}.ip"
elif test -f "${srcdir}/${prog}.input"; then
  INPUT="${srcdir}/${prog}.input"
elif test -f "${srcdir}/${prog}.ip"; then
  INPUT="${srcdir}/${prog}.ip"
fi

OUTPUT=
if test -f "${prog}.output"; then
  OUTPUT="${prog}.output"
elif test -f "${prog}.op"; then
  OUTPUT="${prog}.op"
elif test -f "${srcdir}/${prog}.output"; then
  OUTPUT="${srcdir}/${prog}.output"
elif test -f "${srcdir}/${prog}.op"; then
  OUTPUT="${srcdir}/${prog}.op"
fi

exec 3>&1
if test -n "$INPUT"; then
  if test -n "$OUTPUT"; then
    echo "./${prog} < ${INPUT} | diff ${OUTPUT} -"
    res=`((./${prog} < ${INPUT} 3>&- 4>&-; echo $? 1>&4 3>&- 4>&-) | diff ${OUTPUT} - 1>&3 3>&- 4>&-) 4>&1`
    res2=$?
    test $res = 0 && res=$res2
  else
    echo "./${prog} < ${INPUT}"
    ./${prog} < ${INPUT}
    res=$?
  fi
else
  if test -n "$OUTPUT"; then
    echo "./${prog} | diff ${OUTPUT} -"
    res=`((./${prog} 3>&- 4>&-; echo $? 1>&4 3>&- 4>&-) | diff ${OUTPUT} - 1>&3 3>&- 4>&-) 4>&1`
    res2=$?
    test $res = 0 && res=$res2
  else
    echo "./${prog}"
    ./${prog}
    res=$?
  fi
fi

exit $res
