#! /bin/sh

set -o pipefail

if test -z "$2"; then
  echo usage: $0 srcdir program
  exit -1
fi

srcdir="$1"
prog=`basename $2`
dir=`echo $2 | sed 's/^\(\.\/\)*//g'` # remove preceding './'
if test -n "$dir"; then
  dir=`dirname ${dir}`
  srcdir="${srcdir}/${dir}"
  if test -d "$srcdir"; then :; else
    echo error: $srcdir not found
    exit -1
  fi
  if test -d "$dir"; then :; else
    echo error: $dir not found
    exit -1
  fi
  if test "$dir" != "."; then
    echo -n "[$dir] "
  fi
  cd $dir
fi

INPUT=
if test -f "${prog}.input"; then
  INPUT="${prog}.input"
elif test -f "${prog}.ip"; then
  INPUT="${srcdir}/${prog}.ip"
elif test -f "${srcdir}/${prog}.input"; then
  INPUT="${srcdir}/${prog}.input"
elif test -f "${srcdir}/${prog}.ip"; then
  INPUT="${srcdir}/${prog}.ip"
fi

OUTPUT=
if test -f "${prog}.output"; then
  OUTPUT="${prog}.output"
elif test -f "${prog}.op"; then
  OUTPUT="${srcdir}/${prog}.op"
elif test -f "${srcdir}/${prog}.output"; then
  OUTPUT="${srcdir}/${prog}.output"
elif test -f "${srcdir}/${prog}.op"; then
  OUTPUT="${srcdir}/${prog}.op"
fi

if test -n "$INPUT"; then
  if test -n "$OUTPUT"; then
    echo "./${prog} < ${INPUT} | diff ${OUTPUT} -"
    ./${prog} < ${INPUT} | diff ${OUTPUT} -
  else
    echo "./${prog} < ${INPUT}"
    ./${prog} < ${INPUT}
  fi
else
  if test -n "$OUTPUT"; then
    echo "./${prog} | diff ${OUTPUT} -"
    ./${prog} | diff ${OUTPUT} -
  else
    echo "./${prog}"
    ./${prog}
  fi
fi
