#!/bin/sh

FILE="looper/version.h"

if test -f "$FILE"; then
  DATE=`date +%Y/%m/%d`
  # VER="3.2b5"
  VER="3.2b4-`date +%Y%m%d`"
  awk '$2=="LOOPER_VERSION" {$3=v} $2=="LOOPER_DATE" {$3=d} {print}' v="\"$VER\"" d="\"$DATE\"" "$FILE" > "$FILE.new"
  diff "$FILE" "$FILE.new" > /dev/null 2>&1
  if test "$?" != 0; then
    /bin/cp -f "$FILE.new" "$FILE"
    /bin/echo "$FILE is updated"
    /bin/echo -n "running bootstrap... "
    /bin/sh bootstrap > /dev/null || exit $?
    /bin/echo "done"
    /bin/echo "date    = $DATE"
    /bin/echo "version = $VER"
  fi
  rm -f "$FILE.new"
fi
