#!/bin/sh

VERSION_H=`find . -name version.h`

. config/version.in

awk '$2 ~ /_VERSION$/ {$3=v} $2 ~ /_DATE$/ {$3=d} {print}' v="\"$VER\"" d="\"$DATE\"" "$VERSION_H" > "$VERSION_H.new"

diff "$VERSION_H" "$VERSION_H.new" > /dev/null 2>&1
if test "$?" != 0; then
  cp -f "$VERSION_H.new" "$VERSION_H"
  echo "$VERSION_H is updated"
  echo "running bootstrap... "
  sh bootstrap > /dev/null || exit $?
  echo "new date    = $DATE"
  echo "new version = $VER"
else
  echo "$VERSION_H is up-to-date"
fi

rm -f "$VERSION_H.new"
