#!/bin/sh

FILE="looper/version.h"

if test -f "$FILE"; then
  DATE=`date +%Y/%m/%d`
  # VER="3.2b3"
  VER="3.2b2-`date +%Y%m%d`"
  awk '$2=="LOOPER_VERSION" {$3=v} $2=="LOOPER_DATE" {$3=d} {print}' v="\"$VER\"" d="\"$DATE\"" "$FILE" > "$FILE.new"
  diff "$FILE" "$FILE.new" > /dev/null 2>&1
  if test "$?" != 0; then
    cp -f "$FILE.new" "$FILE"
    echo "$FILE is updated"
    echo -n "running bootstrap... "
    sh bootstrap > /dev/null || exit $?
    echo "done"
    echo "date    = $DATE"
    echo "version = $VER"
  fi
  rm -f "$FILE.new"
fi
