/**************************************************************************** 
*
* alps/looper: multi-cluster quantum Monte Carlo algorithm for spin systems
*              in path-integral and SSE representations
*
* $Id: fill_duration.h 455 2003-10-22 01:04:57Z wistaria $
*
* Copyright (C) 1997-2003 by Synge Todo <wistaria@comp-phys.org>,
*
* Permission is hereby granted, free of charge, to any person or organization 
* obtaining a copy of the software covered by this license (the "Software") 
* to use, reproduce, display, distribute, execute, and transmit the Software, 
* and to prepare derivative works of the Software, and to permit others
* to do so for non-commerical academic use, all subject to the following:
*
* The copyright notice in the Software and this entire statement, including 
* the above license grant, this restriction and the following disclaimer, 
* must be included in all copies of the Software, in whole or in part, and 
* all derivative works of the Software, unless such copies or derivative 
* works are solely in the form of machine-executable object code generated by 
* a source language processor.
*
* In any scientific publication based in part or wholly on the Software, the
* use of the Software has to be acknowledged and the publications quoted
* on the web page http://www.alps.org/license/ have to be referenced.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
**************************************************************************/

#ifndef LOOPER_FILL_DURATION_H
#define LOOPER_FILL_DURATION_H

#include <boost/random/exponential_distribution.hpp>
#include <boost/throw_exception.hpp>
#include <stdexcept>

namespace looper {

// fill duration [0,tmax] uniformly with density r

template<class RNG, class C>
void fill_duration(RNG& uniform_01, C& array, 
		   typename C::value_type r, typename C::value_type tmax)
{
  typedef typename C::value_type value_type;

  if (tmax < value_type(0.))
    boost::throw_exception(std::invalid_argument("invalid argument"));

  array.clear();
  if (r <= value_type(0.)) return;

  boost::exponential_distribution<value_type> exp_rng(r);
  value_type t(value_type(0.));
  while (true) {
    t += exp_rng(uniform_01);
    if (t >= tmax) break;
    array.push_back(t);
  }
}

// fill duration [0,1] uniformly with density r

template<class RNG, class C>
void fill_duration(RNG& uniform_01, C& array, typename C::value_type r)
{
  typedef typename C::value_type value_type;
  fill_duration(uniform_01, array, r, value_type(1.));
}

} // end namespace looper

#endif // LOOPER_FILL_DURATION_H
